### ISSUE TITLE
Translate buttons using i18n API

### ISSUE THREAD

**Issue by timurvafin** [fs/rails-base#258]
@vast @VladimirMikhailov Rails has build in support for buttons translation https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L1854

```yml
en:
  helpers:
    submit:
      post:
        create: "Create awesome post"
        update: "Update awesome post"
```

```erb
<%= form_for @post do |f| %>
  <%= f.button :create %>
<% end %>
```

Right now we do not use this API and set button name directly in the views https://github.com/fs/rails-base/blob/master/app/views/devise/registrations/edit.html.slim#L24

After merging https://github.com/fs/rails-base/pull/198 we have following logic:
* do not translate views
* except: titles and simple_form helpers

The questions is: should we translate submit helper using i18n API?
